### PR TITLE
implemented registration popup

### PR DESCRIPTION
**Pull request by hohashvili**
created branch from [OksankaV_#16_implement_AddClubPopUpComponent](https://github.com/UA-1115-TAQC/speak_ukrainian_ta/tree/OksankaV_%2316_implement_AddClubPopUpComponent) to use BasePopUp class form OksankaV

### CODE REVIEW

**Comment by OksankaV** [comment]
It's previous version of BasePopUp class. There is new one (with rootElement) already merged to develop branch. Please, make a rebase.

**Comment by lhalam** [comment]
ToDo update

**Comment by lhalam** [comment]
update to use pageFactory in `RegistrationPopupComponent.java`

**Comment by hohashvili** [comment]
refactored everything to [registration-popup-dev](https://github.com/UA-1115-TAQC/speak_ukrainian_ta/tree/registration-popup-dev)

**Pull request closed without merging**
